version: '3'
services:
  nginx:
    image: "jwilder/nginx-proxy:latest"
    container_name: "portfolio-nginx"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "unless-stopped"
    networks: 
      - "portfolio"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST}

  letsencrypt:
    image: "nginxproxy/acme-companion:latest"
    container_name: "portfolio-letsencrypt"
    volumes:
      - "acme:/etc/acme.sh"
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_PROXY_CONTAINER=${NGINX_PROXY_CONTAINER}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
    restart: "unless-stopped"
    depends_on:
      - "nginx"
    networks: 
      - "portfolio"

volumes:
  acme: {}
  html: {}
  vhost: {}
  dhparam: {}
  certs: {}


networks:
  portfolio:
    name: portfolio
    external: true